apiVersion: v1
kind: Secret
metadata:
  name: ords-secret
  namespace: ords-zoo
type: Opaque
stringData:
  admin_user: sys
  admin_pwd: MyDBPassword  # This should match your ORACLE_PWD from the docker run command
  proxy_pwd: oracle
  db_host: 192.168.49.1  # Special hostname to access the host machine from minikube
  db_port: "1521"
  db_servicename: ORCLPDB1